apiVersion: v1
kind: Pod
metadata:
  labels:
    run: splunk
  name: splunk
spec:
  containers:
  - image: nginx
    name: splunk
    volumeMounts:
      - name: app-config
        mountPath: /etc/config
  volumes:
    - name: app-config
      configMap:
        name: app-config
