apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: rc-nginx
  name: rc-nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: rc-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
