apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kplabs-cmdargs
  name: kplabs-cmdargs
spec:
  containers:
  - image: busybox
    name: cmdcontainer
    command:
    - "sleep"
    - "3600"
