apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: kplabs-selector
  name: kplabs-selector
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kplabs-selector
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: kplabs-selector
    spec:
      containers:
      - image: nginx
        name: kplabs-selector
        resources: {}
status: {}
