apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  labels:
    run: kplabs-job
  name: kplabs-job
spec:
  concurrencyPolicy: Allow
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            run: kplabs-job
        spec:
          containers:
          - args:
            - date
            image: ubuntu
            name: kplabs-job
            resources: {}
          restartPolicy: OnFailure
  schedule: '* * * * *'
status: {}
