apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      args:
        - while true; do echo -en '\n'; printf fqdn=$fqdn'\n'; sleep 30; done;
      command:
        - sh
        - -c
      image: busybox
      env:
        - name: fqdn
          value: "$(host):$(port)"
      envFrom:
        - configMapRef:
            name: test
