apiVersion: v1
kind: Pod
metadata:
  name: test2
spec:
  containers:
    - name: test2
      args:
        - while true; do echo -en '\n'; printf fqdn=$fqdn'\n'; printf host=$host'\n'; printf port=$port'\n'; sleep 30; done;
      command:
        - sh
        - -c
      image: busybox
      env:
        - name: fqdn
          value: "$(host):$(port)"
      envFrom:
        - configMapRef:
            name: test
